In [2]:
import sys
sys.path.append('..')
from datasets import KusisqaDim
from datasets.utils import randomcrop, centercrop
from torch.utils.data import DataLoader

# dataset_train = KusisqaDim(
#     "../ser_datasets/test_kusisqa/audio-alegre.csv",
#     "../ser_datasets/test_kusisqa/Audio-Alegre/",
#     transform=[centercrop],
# )

dataset_train = KusisqaDim(
    "../ser_datasets/test_kusisqa/audio-alegre.csv",
    "../ser_datasets/test_kusisqa/Audio-Alegre/",
    transform=[centercrop],
)

train_dataloader = DataLoader(
    dataset_train,
    batch_size=32,
    shuffle=False,
    num_workers=3,
    persistent_workers=True,
)

for x,y in train_dataloader:
    print(x.shape, y.shape)
    break

torch.Size([32, 64, 128]) torch.Size([32, 3])


In [41]:
from models.cnn_dim import CNNDim

model = CNNDim.load_from_checkpoint("../logs/kusisqa_ccc/dot8kgqa/checkpoints/epoch=9-step=479.ckpt",lr=0.001)

# print(model.learning_rate)
# prints the learning_rate you used in this checkpoint

model.eval()

for x,y in train_dataloader:
  resultado = model(x)
  for i in range(len(resultado)):
    print(resultado[i].data, y[i])
  
  break


/home/luisbch/.local/lib/python3.8/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor([2.9579, 2.1445, 3.9237]) tensor([5., 4., 5.])
tensor([2.8535, 2.3622, 3.6735]) tensor([5., 4., 5.])
tensor([2.4372, 1.7594, 2.9781]) tensor([5., 4., 5.])
tensor([2.5489, 2.0620, 3.4217]) tensor([5., 4., 5.])
tensor([2.4598, 2.2247, 2.8442]) tensor([5., 4., 5.])
tensor([2.1250, 1.4912, 2.8644]) tensor([4., 2., 5.])
tensor([2.2166, 1.7539, 2.9273]) tensor([4., 2., 5.])
tensor([2.1129, 1.7675, 2.8982]) tensor([4., 2., 5.])
tensor([2.6462, 2.5861, 3.1654]) tensor([5., 4., 5.])
tensor([1.7023, 1.5733, 2.4109]) tensor([5., 4., 4.])
tensor([2.6735, 2.7285, 3.0088]) tensor([5., 4., 5.])
tensor([2.5481, 3.0122, 2.9603]) tensor([5., 4., 5.])
tensor([2.8977, 2.6400, 3.0697]) tensor([5., 4., 5.])
tensor([2.0736, 2.0252, 2.6347]) tensor([4., 2., 4.])
tensor([2.6673, 4.5948, 2.8334]) tensor([5., 4., 5.])
tensor([1.1296, 2.0319, 2.0217]) tensor([3., 2., 4.])
tensor([2.0766, 1.3705, 2.8005]) tensor([4., 2., 4.])
tensor([1.7805, 1.3918, 2.3369]) tensor([2., 2., 4.])
tensor([2.0068, 1.5052, 2.14

In [54]:
path_pesos = "../logs/kusisqa_ccc/2rrt54ay/checkpoints/epoch=63-step=3071.ckpt"
from models.cnn_dim import CNNDim
from models.metrics import CCC

model = CNNDim.load_from_checkpoint(path_pesos,lr=0.001)
model.eval()

from torchmetrics import MeanAbsoluteError
metric = MeanAbsoluteError()
for x,y in train_dataloader:
  resultado = model(x)
  acc = metric(resultado, y)
  print(f"Accuracy on batch: { acc}")
  
acc = metric.compute()
print(f"Accuracy on all data: {acc}")


Accuracy on batch: 0.9122545123100281
Accuracy on batch: 0.8550463318824768
Accuracy on all data: 0.8845731616020203


## TRISTE

In [5]:
dataset_train = KusisqaDim(
    "../ser_datasets/test_kusisqa/audio-triste.csv",
    "../ser_datasets/test_kusisqa/Audio-Triste/",
    transform=[centercrop],
)

train_dataloader = DataLoader(
    dataset_train,
    batch_size=32,
    shuffle=False,
    num_workers=3,
    persistent_workers=True,
)

for x,y in train_dataloader:
    print(x.shape, y.shape)
    break

path_pesos = "../checkpoints/epoch=222-step=5351.ckpt"
from models.cnn_dim import CNNDim
from models.metrics import CCC

model = CNNDim.load_from_checkpoint(path_pesos,lr=0.001)
model.eval()

metric = MeanAbsoluteError()
for x,y in train_dataloader:
  resultado = model(x)
  acc = metric(resultado, y)
  for i in range(len(resultado)):
    print(resultado[i].data, y[i])
  print(f"MAE batch: { acc}")
  
acc = metric.compute()
print(f"MAE: { acc}")


torch.Size([32, 64, 128]) torch.Size([32, 3])


NameError: name 'MeanAbsoluteError' is not defined

## Alegre

In [59]:
dataset_train = KusisqaDim(
    "../ser_datasets/test_kusisqa/audio-alegre.csv",
    "../ser_datasets/test_kusisqa/Audio-Alegre/",
    transform=[centercrop],
)

train_dataloader = DataLoader(
    dataset_train,
    batch_size=32,
    shuffle=False,
    num_workers=3,
    persistent_workers=True,
)

for x,y in train_dataloader:
    print(x.shape, y.shape)
    break

path_pesos = "../logs/kusisqa_ccc/2rrt54ay/checkpoints/epoch=63-step=3071.ckpt"
from models.cnn_dim import CNNDim
from models.metrics import CCC

model = CNNDim.load_from_checkpoint(path_pesos,lr=0.001)
model.eval()

metric = MeanAbsoluteError()
for x,y in train_dataloader:
  resultado = model(x)
  acc = metric(resultado, y)
  for i in range(len(resultado)):
    print(resultado[i].data, y[i])
  print(f"MAE batch: { acc}")
  
acc = metric.compute()
print(f"MAE: { acc}")


torch.Size([32, 64, 128]) torch.Size([32, 3])
tensor([3.2521, 2.6007, 4.4864]) tensor([5., 4., 5.])
tensor([3.7965, 2.7649, 3.8055]) tensor([5., 4., 5.])
tensor([4.1385, 2.7048, 4.0928]) tensor([5., 4., 5.])
tensor([3.1979, 3.0571, 3.2159]) tensor([5., 4., 5.])
tensor([3.6597, 2.9202, 3.9953]) tensor([5., 4., 5.])
tensor([3.1832, 2.2277, 3.4002]) tensor([4., 2., 5.])
tensor([2.6669, 1.9871, 3.2333]) tensor([4., 2., 5.])
tensor([2.6341, 2.2736, 3.5712]) tensor([4., 2., 5.])
tensor([3.0214, 2.5459, 3.0417]) tensor([5., 4., 5.])
tensor([2.4021, 3.0157, 2.8730]) tensor([5., 4., 4.])
tensor([3.7051, 2.7452, 3.6406]) tensor([5., 4., 5.])
tensor([3.4122, 3.1411, 3.8151]) tensor([5., 4., 5.])
tensor([4.8600, 3.0570, 4.7074]) tensor([5., 4., 5.])
tensor([2.4780, 2.4321, 3.0252]) tensor([4., 2., 4.])
tensor([3.7312, 3.8554, 3.5990]) tensor([5., 4., 5.])
tensor([1.6940, 3.0005, 2.8840]) tensor([3., 2., 4.])
tensor([2.4270, 1.9006, 3.1846]) tensor([4., 2., 4.])
tensor([2.6434, 1.8302, 2.9024]) ten