## Triste

In [26]:
import sys
sys.path.append('..')
from datasets import KusisqaDim
from datasets.utils import randomcrop, centercrop
from torch.utils.data import DataLoader
from torchmetrics import MeanAbsoluteError

dataset_train = KusisqaDim(
    "../ser_datasets/test_kusisqa/audio-triste.csv",
    "../ser_datasets/test_kusisqa/Audio-Triste/",
    transform=[centercrop],
)

train_dataloader = DataLoader(
    dataset_train,
    batch_size=32,
    shuffle=False,
    num_workers=3,
    persistent_workers=True,
)

for x,y in train_dataloader:
    print(x.shape, y.shape)
    break

path_pesos = "../checkpoints/flower.ckpt"
from models.cnn_dim import CNNDim
from models.metrics import CCC, ccc

model = CNNDim.load_from_checkpoint(path_pesos,lr=0.001)
model.eval()

metric = MeanAbsoluteError()

ccc_v = CCC()
ccc_a = CCC()
ccc_d = CCC()

for x,y in train_dataloader:
  resultado = model(x)
  
  acc = metric(resultado, y)

  mccc_v = ccc(resultado[:, 0], y[:, 0])
  mccc_a = ccc(resultado[:, 1], y[:, 1])
  mccc_d = ccc(resultado[:, 2], y[:, 2])

  ccc_v(mccc_v)
  ccc_a(mccc_a)
  ccc_d(mccc_d)


  for i in range(len(resultado)):
    print(resultado[i].data, y[i])
    
  print(f"MAE batch: { acc}")

  print(f"CCC V batch: { mccc_v}")
  print(f"CCC A batch: { mccc_a}")
  print(f"CCC D batch: { mccc_d}\n")

  
acc = metric.compute()
mccc_a = ccc_a.compute()
mccc_v = ccc_v.compute()
mccc_d = ccc_d.compute()

print(f"MAE: { acc}")
print(f"CCC V: { mccc_v}")
print(f"CCC A : { mccc_a}")
print(f"CCC D : { mccc_d}")

# Plot confusion matrix
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt



torch.Size([32, 64, 128]) torch.Size([32, 3])
tensor([1.1971, 2.3734, 1.7973]) tensor([3., 1., 2.])
tensor([1.5289, 1.9064, 2.0531]) tensor([3., 1., 2.])
tensor([1.6092, 2.2429, 2.0536]) tensor([3., 1., 4.])
tensor([1.6721, 2.7988, 2.1829]) tensor([3., 1., 4.])
tensor([0.2473, 3.2732, 1.1962]) tensor([1., 2., 1.])
tensor([1.3738, 3.0098, 2.3785]) tensor([1., 2., 1.])
tensor([1.2797, 2.7084, 1.8717]) tensor([1., 2., 1.])
tensor([1.6935, 1.9569, 2.3324]) tensor([1., 2., 1.])
tensor([1.2349, 2.7425, 1.8202]) tensor([1., 2., 1.])
tensor([1.4915, 2.0907, 1.9435]) tensor([1., 2., 1.])
tensor([2.3762, 2.1761, 2.7596]) tensor([1., 2., 1.])
tensor([1.3939, 2.3153, 2.2033]) tensor([1., 2., 1.])
tensor([1.3348, 2.3790, 2.1377]) tensor([1., 2., 1.])
tensor([1.5908, 2.5098, 2.1831]) tensor([1., 2., 1.])
tensor([1.7497, 2.1137, 1.9633]) tensor([1., 2., 1.])
tensor([1.0341, 2.7343, 1.7694]) tensor([1., 2., 1.])
tensor([1.9815, 2.1989, 2.4973]) tensor([1., 2., 1.])
tensor([1.4355, 3.0477, 2.0564]) ten

## Alegre

In [24]:
dataset_train = KusisqaDim(
    "../ser_datasets/test_kusisqa/audio-alegre.csv",
    "../ser_datasets/test_kusisqa/Audio-Alegre/",
    transform=[centercrop],
)

train_dataloader = DataLoader(
    dataset_train,
    batch_size=32,
    shuffle=False,
    num_workers=3,
    persistent_workers=True,
)

for x,y in train_dataloader:
    print(x.shape, y.shape)
    break

path_pesos = "../checkpoints/flower.ckpt"
from models.cnn_dim import CNNDim
from models.metrics import CCC

model = CNNDim.load_from_checkpoint(path_pesos,lr=0.001)
model.eval()

metric = MeanAbsoluteError()

ccc_v = CCC()
ccc_a = CCC()
ccc_d = CCC()

for x,y in train_dataloader:
  resultado = model(x)
  
  acc = metric(resultado, y)

  mccc_v = ccc(resultado[:, 0], y[:, 0])
  mccc_a = ccc(resultado[:, 1], y[:, 1])
  mccc_d = ccc(resultado[:, 2], y[:, 2])

  ccc_v(mccc_v)
  ccc_a(mccc_a)
  ccc_d(mccc_d)


  # for i in range(len(resultado)):
  #   print(resultado[i].data, y[i])
    
  print(f"MAE batch: { acc}")

  print(f"CCC V batch: { mccc_v}")
  print(f"CCC A batch: { mccc_a}")
  print(f"CCC D batch: { mccc_d}\n")

  
acc = metric.compute()
mccc_a = ccc_a.compute()
mccc_v = ccc_v.compute()
mccc_d = ccc_d.compute()

print(f"MAE: { acc}")
print(f"CCC V: { mccc_v}") 
print(f"CCC A : { mccc_a}")
print(f"CCC D : { mccc_d}")

torch.Size([32, 64, 128]) torch.Size([32, 3])
MAE batch: 0.8071368336677551
CCC V batch: 0.07900616526603699
CCC A batch: 0.3999749720096588
CCC D batch: 0.0535859577357769

MAE batch: 0.8884741067886353
CCC V batch: 0.18282510340213776
CCC A batch: 0.20438623428344727
CCC D batch: 0.0

MAE: 0.8464936017990112
CCC V: 0.13091564178466797
CCC A : 0.30218058824539185
CCC D : 0.02679297886788845
